CREATE TABLE `METRICS` (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`SCRAPING_DATE`	INTEGER NOT NULL,
	`SEEDERS_NUMBER`	INTEGER,
	`LEECHERS_NUMBER`	INTEGER,
	`RATIO`	NUMERIC,
	`TORRENT_ID`	INTEGER,
	FOREIGN KEY(`TORRENT_ID`) REFERENCES `TORRENTS`(`ID`)
);

CREATE TABLE `TORRENTS` (
	`NAME`	TEXT NOT NULL,
	`SIZE`	NUMERIC,
	`ALIVE`	INTEGER,
	`CATEGORY`	TEXT NOT NULL,
	`ID`	INTEGER PRIMARY KEY,
	`SUB_CATEGORY`	TEXT NOT NULL
);